### ISSUE TITLE
Project Usage

### ISSUE THREAD

**Issue by softcare65** [webstarlee/wallet-finder#1]
Hi, webstarlee.

Hope, you are doing well.
I just want to know about your this project "wallet-finder".
What can I do with it ?

I hope I can get any response from you soon.

Best Regards.

**Comment by danielleeas** [comment]
It's just generate random wallet address with private key.
we detect wallet transaction history, if that wallet has transactions ast least one.
we will save that wallet pub and private.
we can hack wallet with this method.
but this is really impossible i think,
But peoples has dream...
